### DISCUSSION TITLE
How can I make popular tags on the home page visible by language tag?

### DISCUSSION THREAD

**Discussion by ayyilmaz** [Inoryum-Ltd/aesto#8] [Q&A]
How can I make popular tags on the home page visible by language tag? Currently I use ınternal tags for listing posts by language on homapage and it is working but not for popular tags. My main language is Turkish and posts in Turkish continue to appear in English internal tag homepage. Turkish posts are not shown on main listing but they are shown at popular tags section although ı changed language from Turkish to English.

SS: https://i.ibb.co/DYgqhW8/insttt.png
![insttt](https://user-images.githubusercontent.com/24845098/103378044-251b0180-4af2-11eb-9086-6fe494309a2a.png)

my routes.yaml file

```
routes:
  /signup/: members/signup
  /signin/: members/signin
  /account/: members/account

collections:
  /:
    permalink: /{slug}/
    template: index
    filter: 'tag:-[hash-en,hash-nd]'
  /en/:
    permalink: /en/{slug}/
    template: index-en
    filter: 'tag:hash-en'
  /nd/:
    permalink: /nd/{slug}/
    template: index-nd
    filter: 'tag:hash-nd'

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
```
